env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"

task:
    name: new88
    timeout_in: 120m
    container:
      image: ubuntu:latest
      cpu: 16
      memory: 24G
#    download_ccache_script:
#      - ./download_ccache
    sync_script:
      - ./sync
    build_script:
      - ./build
#    upload_ccache_script:
#      - ./upload_ccache
      
